name: Serverless Weather Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: satak/webrequest-action@master
        with:
          method: GET
          url: https://serverless-cron.vercel.app/api/weather?token=${{ secrets.TOKEN }}

